-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ZynqBF_2tx_fpga\ZynqBF_2t_ip_src_rx_bram.vhd
-- Created: 2019-02-08 23:33:52
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ZynqBF_2t_ip_src_rx_bram
-- Source Path: ZynqBF_2tx_fpga/channel_estimator/rx_bram
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ZynqBF_2t_ip_src_ZynqBF_2tx_fpga_pkg.ALL;

LIBRARY UNISIM;
use UNISIM.vcomponents.all;

LIBRARY UNIMACRO;
use UNIMACRO.vcomponents.all;

ENTITY ZynqBF_2t_ip_src_rx_gs_mult IS
  GENERIC( N                              :   integer := 2;     -- number of channels
           NDSP                           :   integer := 64     -- number of DSPs to use for multiply-accumulate
        );
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        en                                :   IN    std_logic;  -- enable for MACC
        rxi                               :   IN    vector_of_std_logic_vector16(0 TO (NDSP-1));  -- rx i data for the correlators
        rxq                               :   IN    vector_of_std_logic_vector16(0 TO (NDSP-1));  -- rx q data for the correlators
        gsi                               :   IN    vector_of_std_logic_vector16(0 TO (NDSP*N-1));  -- gs i data for the correlators
        gsq                               :   IN    vector_of_std_logic_vector16(0 TO (NDSP*N-1))   -- gs q data for the correlators
        );
END ZynqBF_2t_ip_src_rx_gs_mult;


ARCHITECTURE rtl OF ZynqBF_2t_ip_src_rx_gs_mult IS

  component rx_gs_mult_core
    generic( NDSP                           :   integer := 64);   -- number of DSPs to use for multiply-accumulate
    port( clk                               :   IN    std_logic;
          reset                             :   IN    std_logic;
          enb                               :   IN    std_logic;
          en                                :   IN    std_logic;  -- enable for MACC
          rxi                               :   IN    vector_of_std_logic_vector16(0 TO (NDSP-1));  -- rx i data for the multipy-accumulator
          rxq                               :   IN    vector_of_std_logic_vector16(0 TO (NDSP-1));  -- rx q data for the multipy-accumulator
          gsi                               :   IN    vector_of_std_logic_vector16(0 TO (NDSP-1));  -- gs i data for the multipy-accumulator
          gsq                               :   IN    vector_of_std_logic_vector16(0 TO (NDSP-1))   -- gs q data for the multipy-accumulator
    );
  end component;
        

  FOR ALL : ZynqBF_2t_ip_src_rx_gs_mult_core
    USE ENTITY: work.ZynqBF_2t_ip_src_rx_gs_mult_core(rtl);
        
BEGIN
   
  gen_rx_gs_mult_cores : for i in 1 to N generate
    rx_gs_mult_core_i : rx_gs_mult_core
        generic map( NDSP => NDSP)
        port map( 
            clk => clk,
            reset => reset,
            enb => enb,
            en => en,
            rxi => rxi,
            rxq => rxq,
            gsi => gsi(NDSP*(i-1) to (NDSP*i - 1)),
            gsq => gsq(NDSP*(i-1) to (NDSP*i - 1))
        );
  end generate;
                

END rtl;

